// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoVIXgil64d3ffaYgWaxWSR65z8a1p6E',
    appId: '1:1086982258297:web:d25388234bb418674b1ea8',
    messagingSenderId: '1086982258297',
    projectId: 'todo-6f854',
    authDomain: 'todo-6f854.firebaseapp.com',
    storageBucket: 'todo-6f854.appspot.com',
    measurementId: 'G-QNE2VGKEWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgLvsH2s_cWJl2GXLcuvF7r9RADnPfJ8',
    appId: '1:1086982258297:android:c7f3caa4c4e050c04b1ea8',
    messagingSenderId: '1086982258297',
    projectId: 'todo-6f854',
    storageBucket: 'todo-6f854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVyVM-xDTf1a7EIs0_3xKyXEezkiu9lA',
    appId: '1:1086982258297:ios:681d00b9a39873554b1ea8',
    messagingSenderId: '1086982258297',
    projectId: 'todo-6f854',
    storageBucket: 'todo-6f854.appspot.com',
    iosClientId:
        '1086982258297-27ap63hqmckfaqf6ldadqv9tla9q0asd.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCVyVM-xDTf1a7EIs0_3xKyXEezkiu9lA',
    appId: '1:1086982258297:ios:6332da91fae5d37e4b1ea8',
    messagingSenderId: '1086982258297',
    projectId: 'todo-6f854',
    storageBucket: 'todo-6f854.appspot.com',
    iosClientId:
        '1086982258297-kvh2hcdu69hp615ggebaoj7h874ouoeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
