// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKZQWh7_m35fVgWskOOq39kijc-MJJJs',
    appId: '1:602289810413:web:d5704b7f6e98007cc295e4',
    messagingSenderId: '602289810413',
    projectId: 'todo-5ea16',
    authDomain: 'todo-5ea16.firebaseapp.com',
    storageBucket: 'todo-5ea16.appspot.com',
    measurementId: 'G-9V3LFBED6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzh5U0vg66gp0Zf2p_PXi9R_Xx-DGpQU',
    appId: '1:602289810413:android:c5e5637471f919d8c295e4',
    messagingSenderId: '602289810413',
    projectId: 'todo-5ea16',
    storageBucket: 'todo-5ea16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOCHUEGLwdCcBabiOs52JIdo9U4ajVhY',
    appId: '1:602289810413:ios:0d43a29377962ea4c295e4',
    messagingSenderId: '602289810413',
    projectId: 'todo-5ea16',
    storageBucket: 'todo-5ea16.appspot.com',
    iosClientId: '602289810413-uim6p31khikmdracs9rhm95bkptj7db7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOCHUEGLwdCcBabiOs52JIdo9U4ajVhY',
    appId: '1:602289810413:ios:c86766064b3a1c3fc295e4',
    messagingSenderId: '602289810413',
    projectId: 'todo-5ea16',
    storageBucket: 'todo-5ea16.appspot.com',
    iosClientId: '602289810413-bu08kb1t7ptucavhmi7cpp383hjpe460.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
